[package]
name = "rs-laseration"
version = "0.1.0"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
edition = "2018"

[dependencies]
rltk = { version = "*" }
legion = { git = "https://github.com/TomGillen/legion" }
tracing-subscriber = "*"
